# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 12:22
from __future__ import unicode_literals

import difesa_del_suolo_criticita.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difesa_del_suolo_criticita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segnalazione',
            name='nota_segnalazione',
            field=models.FileField(db_column='nota_segn', null=True, upload_to=difesa_del_suolo_criticita.models.nota_segnalazione_user_directory_path),
        ),
    ]
