# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 12:33
from __future__ import unicode_literals

import difesa_del_suolo_criticita.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difesa_del_suolo_criticita', '0003_auto_20160824_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentazionecollegata',
            name='documento_collegato',
            field=models.FileField(blank=True, db_column='doc_coll', null=True, upload_to=difesa_del_suolo_criticita.models.documento_collegato_user_directory_path),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='nota_risposta',
            field=models.FileField(blank=True, db_column='nota_risp', null=True, upload_to=difesa_del_suolo_criticita.models.nota_risposta_user_directory_path),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='relazione_sopralluogo',
            field=models.FileField(blank=True, db_column='rel_sopr', null=True, upload_to=difesa_del_suolo_criticita.models.relazione_sopralluogo_user_directory_path),
        ),
    ]
