# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difesa_del_suolo_criticita', '0005_auto_20160824_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segnalazione',
            name='codice_segnalazione',
            field=models.CharField(db_column='codsegn', max_length=20, unique=True),
        ),
    ]
