#!/bin/bash

python2.7 /opt/PORTALE_SEGNALAZIONI/portale_segnalazioni/send_mail_segnalazioni_script/send_mail_segnalazioni_prova_lamma.py
python2.7 /opt/PORTALE_SEGNALAZIONI/portale_segnalazioni/send_mail_segnalazioni_script/send_mail_segnalazioni_assetto_idrogeo.py
python2.7 /opt/PORTALE_SEGNALAZIONI/portale_segnalazioni/send_mail_segnalazioni_script/send_mail_segnalazioni_protezione_civile.py
python2.7 /opt/PORTALE_SEGNALAZIONI/portale_segnalazioni/send_mail_segnalazioni_script/send_mail_segnalazioni_toscana_nord.py
python2.7 /opt/PORTALE_SEGNALAZIONI/portale_segnalazioni/send_mail_segnalazioni_script/send_mail_segnalazioni_toscana_sud.py
python2.7 /opt/PORTALE_SEGNALAZIONI/portale_segnalazioni/send_mail_segnalazioni_script/send_mail_segnalazioni_valdarno_centrale.py
python2.7 /opt/PORTALE_SEGNALAZIONI/portale_segnalazioni/send_mail_segnalazioni_script/send_mail_segnalazioni_valdarno_inferiore.py
python2.7 /opt/PORTALE_SEGNALAZIONI/portale_segnalazioni/send_mail_segnalazioni_script/send_mail_segnalazioni_valdarno_superiore.py